params:
  seed: 42

  env:
    clip_observations: 5.0
    clip_actions: 1.0

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0.0          # tighter initial exploration than dexterous-hand
        fixed_sigma: True   # learn sigma
    mlp:
      units: [256, 256]
      activation: elu
      d2rl: False
      initializer:
        name: default
      regularizer:
        name: None

  load_checkpoint: False
  load_path: ''

  config:
    name: yam_cube_sort_8192
    env_name: rlgpu
    device: 'cuda:0'
    device_name: 'cuda:0'
    multi_gpu: False

    ppo: True
    mixed_precision: True        # disable AMP to avoid NaN std during policy sampling
    normalize_input: True
    normalize_value: True
    normalize_advantage: True
    value_bootstrap: True

    num_actors: -1                # set by script from num_envs

    reward_shaper:
      scale_value: 0.01            # start here; reduce only if rewards are huge

    gamma: 0.99
    tau: 0.95

    learning_rate: 3e-4
    lr_schedule: adaptive
    schedule_type: standard
    kl_threshold: 0.01

    max_epochs: 800               # manipulation usually needs more than 150
    save_best_after: 50
    save_frequency: 50
    print_stats: True

    grad_norm: 1.0
    truncate_grads: True

    entropy_coef: 0.005           # helps staged behavior exploration
    e_clip: 0.2
    clip_value: True
    critic_coef: 2.0
    bounds_loss_coef: 0.0001

    horizon_length: 32            # 8192 * 32 = 262,144 batch # maybe try 32 for memory?
    minibatch_size: 32768         # 8 minibatches/update # maybe try 32768 for memory?
    mini_epochs: 5                # 40 optimizer steps/update

    # If you are NOT using an RNN, keep seq_length at 1 (or omit it)
    seq_length: 1

    player:
      deterministic: True
      games_num: 100000
      print_stats: True
